import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 20,
    justifyContent: 'center',
  },
  headerText: {
    fontSize: 32,
    fontWeight: '700',
    color: '#5F7282',
    textAlign: 'center',
    marginBottom: 60,
    letterSpacing: 1,
  },
  subHeaderText: {
    fontSize: 16,
    color: '#9D489E',
    textAlign: 'center',
    marginBottom: 20,
  },
  logo: {
    width: 120, // Un poco más grande para que luzca
    height: 120,
    alignSelf: 'center',
    marginBottom: 40,
  },
  logoText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#5F7282',
    textAlign: 'center',
  },
  subLogoText: {
    fontSize: 8,
    color: '#5F7282',
    textAlign: 'center',
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#5F7282',
    marginBottom: 8,
    marginLeft: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F0F0', // Gris muy claro del diseño
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 25,
    height: 55,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#5F7282',
  },
primaryButton: {
    backgroundColor: '#9D489E',
    minHeight: 55,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    marginHorizontal: 15,
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  primaryButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  linkText: {
    color: '#5F7282',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 30,
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  card: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 10,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  questionText: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 15,
  },
  optionButton: {
    backgroundColor: '#EEE',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  optionButtonSelected: {
    backgroundColor: '#00C9A7', // Teal color for selection
  },
  correctOption: {
    backgroundColor: '#FF0055', // Red/Pink for correct/incorrect highlights based on design
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 60,
    left: 20,
  },
  backText: {
    color: '#5F7282',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  descriptionText: {
    fontSize: 16,
    color: '#5F7282',
    textAlign: 'center',
    marginBottom: 40,
    marginTop: -40, // Para acercarlo al título
  },
  inputContainerBorder: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#9D489E', // Borde morado de la imagen
    borderRadius: 15,
    paddingHorizontal: 15,
    marginBottom: 25,
    height: 65, // Un poco más altos como en la imagen
  },
  requirementsContainer: {
    marginTop: 10,
    paddingHorizontal: 10,
  },
  requirementTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#5F7282',
    marginBottom: 10,
  },
  requirementText: {
    fontSize: 14,
    color: '#00A19D', // El color verde/turquesa de los puntos
    marginBottom: 5,
    marginLeft: 10,
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 30,
    paddingHorizontal: 10,
  },
  otpBox: {
    width: 70,
    height: 90,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#9D489E',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  otpText: {
    fontSize: 35,
    fontWeight: 'bold',
    color: '#5F7282',
  },
  timerText: {
    textAlign: 'center',
    color: '#5F7282',
    fontSize: 14,
    marginBottom: 40,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    height: 55,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#9D489E',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginHorizontal: 40,
  },
  secondaryButtonText: {
    color: '#9D489E',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 40,
    marginBottom: 20,
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#5F7282',
    marginVertical: 20,
  },
  mainCard: {
    backgroundColor: '#9D489E',
    borderRadius: 20,
    padding: 25,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  mainCardText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    flex: 1,
    marginLeft: 20,
    letterSpacing: 1,
  },
  iconContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    padding: 10,
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#5F7282',
    marginTop: 20,
    marginBottom: 15,
  },
  progressCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F0F0',
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 5,
    borderLeftColor: '#9D489E',
  },
  progressTextContainer: {
    flex: 1,
    marginLeft: 15,
  },
  progressTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#5F7282',
  },
  progressSub: {
    fontSize: 10,
    color: '#5F7282',
  },
  progressPercent: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#5F7282',
  },
  navbar: {
    flexDirection: 'row',
    backgroundColor: '#9D489E',
    height: 70,
    justifyContent: 'space-around',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  selectContainer: {
    backgroundColor: '#F0F2F3',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  selectText: {
    color: '#A0AAB2',
    fontSize: 14,
    fontWeight: '600',
  },
  questionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginVertical: 15,
  },
  questionOption: {
    width: '48%',
    backgroundColor: '#F0F2F3',
    height: 60,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionOptionSelected: {
    backgroundColor: '#9D489E',
  },
  questionOptionText: {
    color: '#5F7282',
    fontWeight: 'bold',
    fontSize: 13,
  },
  historialButton: {
    backgroundColor: '#9D489E',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderRadius: 30,
    padding: 30,
    width: '90%',
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#5F7282',
    marginTop: 15,
  },
  modalResult: {
    fontSize: 18,
    color: '#5F7282',
    marginVertical: 20,
  },
  resultBold: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#5F7282',
  },
  historyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F2F3',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    borderLeftWidth: 6,
    borderLeftColor: '#9D489E',
  },
  historyIconCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  historyInfoContainer: {
    flex: 1,
  },
  historyTitleText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#5F7282',
  },
  historySubTitleText: {
    fontSize: 10,
    color: '#5F7282',
    marginVertical: 2,
  },
  historyDateText: {
    fontSize: 9,
    color: '#A0AAB2',
  },
  historyVerMasButton: {
    backgroundColor: '#9D489E',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  historyVerMasText: {
    color: '#FFF',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // --- ESTILOS PARA EL MODAL DE RESULTADOS (DETALLE) ---
  resultScoreCard: {
    backgroundColor: '#F0F2F3',
    width: '100%',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    marginBottom: 25,
  },
  resultPercent: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#9D489E',
  },
  resultSubText: {
    color: '#5F7282',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 15,
  },
  resultBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  resultBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  resultBadgeText: {
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  questionReviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  orderBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  questionTextSnippet: {
    flex: 1,
    fontSize: 13,
    color: '#5F7282',
    marginRight: 10,
  },

  // --- UTILIDADES EXTRA ---
  searchSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F2F3',
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 25,
    height: 50,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },

});